Format alias file

diff --git a/aliases b/aliases
--- a/aliases
+++ b/aliases
@@ -9,7 +9,7 @@ alias gdc='git diff --cached'
 alias gmv='git mv'
 alias grm='git rm'
 alias grc='git rm --cached'
-function gc { git commit -m "$*"; }
+function gc() { git commit -m "$*"; }
 alias gl="git log --graph --pretty=format:'%C(yellow)%h%Creset %C(green)%G?%Creset%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'" # pretty log
 alias gpl='git pull'
 alias gpu='git push'
@@ -45,31 +45,31 @@ alias du='du -h'
 # Colorize less using pygmentize if installed
 # Try `$ pip install Pygments` if it's not
 if [ -x "$(command -v pygmentize)" ]; then
-    # Use pygmentize to colorize `less`.
-    # Will not colorize if piped.
-    # I.e.:
-    # $ less script.py  # colorized
-    # $ cat script.py | less  # not colorized
-    # See https://www.meejah.ca/blog/less-pygments for more.
-    export LESSOPEN="| pygmentize %s"
-    # I find I need -X
-    export LESS='-XFR'
-    # ...but do *not* want -X for man-pages
-    export MANPAGER="less -+X -is"
+	# Use pygmentize to colorize `less`.
+	# Will not colorize if piped.
+	# I.e.:
+	# $ less script.py  # colorized
+	# $ cat script.py | less  # not colorized
+	# See https://www.meejah.ca/blog/less-pygments for more.
+	export LESSOPEN="| pygmentize %s"
+	# I find I need -X
+	export LESS='-XFR'
+	# ...but do *not* want -X for man-pages
+	export MANPAGER="less -+X -is"
 fi
 
 # At least colorize man pages
-function man {
-    env \
-        LESS_TERMCAP_mb="$(printf "\e[1;31m")" \
-        LESS_TERMCAP_md="$(printf "\e[1;31m")" \
-        LESS_TERMCAP_me="$(printf "\e[0m")" \
-        LESS_TERMCAP_se="$(printf "\e[0m")" \
-        LESS_TERMCAP_so="$(printf "\e[1;44;33m")" \
-        LESS_TERMCAP_ue="$(printf "\e[0m")" \
-        LESS_TERMCAP_us="$(printf "\e[1;32m")" \
-            man "$@"
-};
+function man() {
+	env \
+		LESS_TERMCAP_mb="$(printf "\e[1;31m")" \
+		LESS_TERMCAP_md="$(printf "\e[1;31m")" \
+		LESS_TERMCAP_me="$(printf "\e[0m")" \
+		LESS_TERMCAP_se="$(printf "\e[0m")" \
+		LESS_TERMCAP_so="$(printf "\e[1;44;33m")" \
+		LESS_TERMCAP_ue="$(printf "\e[0m")" \
+		LESS_TERMCAP_us="$(printf "\e[1;32m")" \
+		man "$@"
+}
 
 ###############################################################################
 # Improved Movement
@@ -81,14 +81,18 @@ alias l='ls -CF'
 alias cd..='cd ..' # common typo
 
 # Easily move around directories
-function cdl { cd "$1" || return; ls; }
-function mkcd { mkdir -p -- "$1"; cd -P -- "$1" || return; }
-function up
-{
-    for ((i=1; i<=$1; i++));
-    do
-        cd ..
-    done;
+function cdl() {
+	cd "$1" || return
+	ls
+}
+function mkcd() {
+	mkdir -p -- "$1"
+	cd -P -- "$1" || return
+}
+function up() {
+	for ((i = 1; i <= $1; i++)); do
+		cd ..
+	done
 }
 
 # Better than `which`
@@ -108,14 +112,14 @@ alias T='| tail'
 alias L='| less'
 
 # Alias various `open` commands as `o`
-if  [[ "$OSTYPE" == "darwin"* ]]; then
-    alias o='open'
-elif  [[ "$OSTYPE" == "cygwin" ]]; then
-    alias o='cygstart'
-elif  [[ "$OSTYPE" == "msys" ]]; then
-    alias o='explorer.exe'  # hoping this works
+if [[ "$OSTYPE" == "darwin"* ]]; then
+	alias o='open'
+elif [[ "$OSTYPE" == "cygwin" ]]; then
+	alias o='cygstart'
+elif [[ "$OSTYPE" == "msys" ]]; then
+	alias o='explorer.exe' # hoping this works
 else
-    alias o='xdg-open'
+	alias o='xdg-open'
 fi
 
 # Quick editing and sourcing.
@@ -124,22 +128,22 @@ alias zshrc='$VISUAL $HOME/.zshrc; source $HOME/.zshrc'
 alias localrc='$VISUAL $HOME/.terminalrc/local; source $HOME/.terminalrc/local'
 
 # Useful unarchiver!
-function extract {
-    if [ -f "$1" ] ; then
-        case "$1" in
-            *.tar.bz2) tar xjf "$1"   ;;
-            *.tar.gz)  tar xzf "$1"   ;;
-            *.bz2)     bunzip2 "$1"   ;;
-            *.rar)     rar x "$1"     ;;
-            *.gz)      gunzip "$1"    ;;
-            *.tar)     tar xf "$1"    ;;
-            *.tbz2)    tar xjf "$1"   ;;
-            *.tgz)     tar xzf "$1"   ;;
-            *.zip)     unzip "$1"     ;;
-            *.Z)       uncompress "$1";;
-            *)         echo "'$1' cannot be extracted via extract()";;
-        esac
-    else
-        echo "'$1' is not a valid file"
-    fi
+function extract() {
+	if [ -f "$1" ]; then
+		case "$1" in
+		*.tar.bz2) tar xjf "$1" ;;
+		*.tar.gz) tar xzf "$1" ;;
+		*.bz2) bunzip2 "$1" ;;
+		*.rar) rar x "$1" ;;
+		*.gz) gunzip "$1" ;;
+		*.tar) tar xf "$1" ;;
+		*.tbz2) tar xjf "$1" ;;
+		*.tgz) tar xzf "$1" ;;
+		*.zip) unzip "$1" ;;
+		*.Z) uncompress "$1" ;;
+		*) echo "'$1' cannot be extracted via extract()" ;;
+		esac
+	else
+		echo "'$1' is not a valid file"
+	fi
 }
